version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backendcontainer
    environment:
      DB_HOST: database
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: mydb
    networks:
      - app_network
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontendcontainer
    networks:
      - app_network
    ports:
      - "8080:80"

  database:
    image: postgres:15 # Assurez-vous que vous avez cette version localement
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - app_network
    volumes:
      - pg_data:/var/lib/postgresql/data # Pour persister les données
    ports:
      - "5432:5432"

networks:
  app_network:
    driver: bridge

volumes:
  pg_data: # Volume pour la persistance des données PostgreSQL
