name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
      # Télécharger le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installer les dépendances
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      # Construire le frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

  build-docker:
    runs-on: ubuntu-latest
    needs: frontend-tests  # Attends la réussite des frontend-tests

    steps:
      # Télécharger le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Construire une image Docker pour le frontend
      - name: Build Docker image
        working-directory: ./frontend
        run: docker build -t bde-frontend .

      # Vérifier que l'application démarre correctement dans un environnement Docker
      - name: Test Docker image
        run: docker run -p 80:80 bde-frontend npm run
